### ISSUE TITLE
Set up automatic patching

### ISSUE THREAD

**Issue by radmilak** [elixir-oslo/oncoEnrichR_galaxy#17]
The RHEL8 image. didn't have this set up for some reason, add it like this:
1) sudo dnf install dnf-automatic -y
2) sudo sed -i -e 's/apply_updates = no/apply_updates = yes/g' /etc/dnf/automatic.conf
3) sudo systemctl enable --now dnf-automatic.timer

 New instances with the image should come with this already activated.

**Comment by dtitov** [comment]
Lev says that he's done it already 👌
